### ISSUE TITLE
Configure other options to livereload

### ISSUE THREAD

**Issue by thiago** [gruntjs/grunt-contrib-connect#186] opened 2015-07-03 18:52 UTC
Hello,
I need specify a new src to livereload script loaded from my page to use a proxy.

Reading the [livereload documentation](https://github.com/intesso/connect-livereload#options) I see that is possible, but from grunt-contrib-connect options It's not possible.

My sugestion is change the conditions to receive complete livereload options too if it is passed.

Example:

```
connect: {
   options: {
      port: 8080,
      hostname: 'localhost',
      livereload: {
         port: 35729,
         src: '/livereload/livereload.js'
      }
   }
...
```

ps: Sorry my english is very bad!

**Comment by jamey-taylor** [comment] 2015-11-05 04:57
Agreed.  grunt-contrib-connect handles the libreload attribute different than libreload.js.  grunt-contrib-connect always expects a number.  But it should accept either a number or an object.

To get libreload working on https on an alternate port, I patched my local copy near TODO comment at line 135 of /tasks/connect.js with

```
      var port = (typeof options.livereload === 'object' && options.livereload.port) ? options.livereload.port : livereload;
          middleware.unshift(injectLiveReload({port: port }));
```

**Comment by XhmikosR** [comment] 2018-09-09 07:33
Duplicate of #100.

**Closed by XhmikosR** 2018-09-09 07:33 UTC
