### ISSUE TITLE
Changing content type of files

### ISSUE THREAD

**Issue by Stefany93** [gruntjs/grunt-contrib-connect#242] opened 2018-07-23 00:55 UTC
Can I make the server either serve some files as text/html or force to change their content type?

Backstory, I am uploading files to S3 but in order to remove the .html extension I need to save them as without an extension and then add content type text/html while uploading. I'd like to be able to test them locally in the grunt-contrib-connect server with forcing their content type. Many thanks!

**Comment by Stefany93** [comment] 2018-07-26 19:35
Anyone ? :/

**Comment by XhmikosR** [comment] 2018-09-09 07:02
Duplicate of #243

**Closed by XhmikosR** 2018-09-09 07:02 UTC
